name: sasya
description: Sasya - Plant Recognition App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.10.5
  http: ^1.1.0
  firebase_core: ^2.24.2
  image_picker: ^1.0.4
  cloud_firestore: ^4.17.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
