// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXVzKIwdJn2VqZTyUbbhX0xZE7SHOELrE',
    appId: '1:653154376874:web:71b8e55d424e3ca29d84d3',
    messagingSenderId: '653154376874',
    projectId: 'sasya-aef45',
    authDomain: 'sasya-aef45.firebaseapp.com',
    storageBucket: 'sasya-aef45.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC56jo0g44q9BipGGp61f1xxz6d3bHiC0k',
    appId: '1:653154376874:android:fd7fa767056477d49d84d3',
    messagingSenderId: '653154376874',
    projectId: 'sasya-aef45',
    storageBucket: 'sasya-aef45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyOMar--IgZJtyJqJERaKMKrt0mwugSHE',
    appId: '1:653154376874:ios:9c927ebde16c65569d84d3',
    messagingSenderId: '653154376874',
    projectId: 'sasya-aef45',
    storageBucket: 'sasya-aef45.firebasestorage.app',
    iosBundleId: 'com.example.sasya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyOMar--IgZJtyJqJERaKMKrt0mwugSHE',
    appId: '1:653154376874:ios:9c927ebde16c65569d84d3',
    messagingSenderId: '653154376874',
    projectId: 'sasya-aef45',
    storageBucket: 'sasya-aef45.firebasestorage.app',
    iosBundleId: 'com.example.sasya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXVzKIwdJn2VqZTyUbbhX0xZE7SHOELrE',
    appId: '1:653154376874:web:0e591349810a85a29d84d3',
    messagingSenderId: '653154376874',
    projectId: 'sasya-aef45',
    authDomain: 'sasya-aef45.firebaseapp.com',
    storageBucket: 'sasya-aef45.firebasestorage.app',
  );
}
